### ISSUE TITLE
AS2Servlet Internal error occured, NullPointerException. v3.0.0

### ISSUE THREAD

**Issue by simakas** [OxalisCommunity/oxalis#179]
log snippet follows:

```
2014-10-01 09:40:08,511 ERROR [eu.peppol.inbound.server.AS2Servlet] [] Internal error occured: null 
java.lang.NullPointerException: null
     at org.apache.tomcat.util.http.parser.HttpParser.parseMediaType(HttpParser.java:215) ~[tomcat-coyote-7.0.37.jar:7.0.37]
     at org.apache.tomcat.util.http.parser.MediaTypeCache.parse(MediaTypeCache.java:54) ~[tomcat-coyote-7.0.37.jar:7.0.37]
     at org.apache.catalina.connector.Response.setContentType(Response.java:806) ~[catalina-7.0.37.jar:7.0.37]
     at org.apache.catalina.connector.Response.checkSpecialHeader(Response.java:1119) ~[catalina-7.0.37.jar:7.0.37]
     at org.apache.catalina.connector.Response.setHeader(Response.java:1446) ~[catalina-7.0.37.jar:7.0.37]
     at org.apache.catalina.connector.ResponseFacade.setHeader(ResponseFacade.java:535) ~[catalina-7.0.37.jar:7.0.37]
     at eu.peppol.inbound.server.AS2Servlet.setHeadersForMDN(AS2Servlet.java:207) ~[AS2Servlet.class:na]
     at eu.peppol.inbound.server.AS2Servlet.doPost(AS2Servlet.java:171) ~[AS2Servlet.class:na]
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:647) [tomcat7-servlet-3.0-api-7.0.37.jar:na]
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [tomcat7-servlet-3.0-api-7.0.37.jar:na]
<...>
2014-10-01 09:40:08,511 ERROR [eu.peppol.inbound.server.AS2Servlet] [] Attempting to return MDN with explanatory message and HTTP 500 status
```

environment:
version.oxalis: 3.0.0
version.java: 1.7.0_51
oxalis.operation.mode: PRODUCTION
oxalis.pki.version: V2
tomcat: 7.0.37

**Comment by VijayaKumar2** [comment]
Hi Everyone,

We are using the tomcat version 7.0.55 with oxalis version 3.0.2,
Still we are getting the same exception. Could any one help us?

What is the JAVA version which you people are running the tomcat ? 

We are running with Java 7.

**Comment by simakas** [comment]
version.oxalis: 3.2.0
version.java: 1.8.0_101
Server version: Apache Tomcat/7.0.55

is our current stable setup, 1.8 solves some problems on the receiving end
