### ISSUE TITLE
Build from source fails on TransmissionRequestBuilderTest

### ISSUE THREAD

**Issue by DynamicOperationsFacilitator** [OxalisCommunity/oxalis#198]
Hi!

Attempting to build the current master branch of Oxalis (43629048f0b64ae97667bba889af74c445ea02b7).

One of the test fails, excluding it from the build by removing the .java file containing the test while building results in a successful build. The test appears to rely on an external resource that does not exist.

```
2014-11-26 13:24:19,461 DEBUG [oxalis-com] Constructed SMP url: http://B-770c6f5843e9e302de47ae4026307076.iso6523-actori
d-upis.smk.peppolcentral.org/iso6523-actorid-upis%3A%3A9908%3A991825827/services/busdox-docid-qns%3A%3Aurn%3Aoasis%3Anam
es%3Aspecification%3Aubl%3Aschema%3Axsd%3AInvoice-2%3A%3AInvoice%23%23urn%3Awww.cenbii.eu%3Atransaction%3Abiicoretrdm010
%3Aver1.0%3A%23urn%3Awww.peppol.eu%3Abis%3Apeppol4a%3Aver1.0%23urn%3Awww.difi.no%3Aehf%3Afaktura%3Aver1%3A%3A2.0
Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.625 sec <<< FAILURE!
xmlWithNoSBDH(eu.peppol.outbound.transmission.TransmissionRequestBuilderTest)  Time elapsed: 0.079 sec  <<< FAILURE!
java.lang.RuntimeException: Problem with SMP lookup for participant 9908:991825827 and document type urn:oasis:names:spe
cification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biicoretrdm010:ver1.0:#urn:www.peppol.eu:bis
:peppol4a:ver1.0#urn:www.difi.no:ehf:faktura:ver1::2.0
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1167)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1103)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:997)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:931)
        at eu.peppol.smp.SmpContentRetrieverImpl.getUrlContent(SmpContentRetrieverImpl.java:52)
        at eu.peppol.smp.SmpLookupManagerImpl.fetchContentsOfSmpUrl(SmpLookupManagerImpl.java:412)
        at eu.peppol.smp.SmpLookupManagerImpl.getServiceMetaData(SmpLookupManagerImpl.java:294)
        at eu.peppol.smp.SmpLookupManagerImpl.getEndpointType(SmpLookupManagerImpl.java:432)
        at eu.peppol.smp.SmpLookupManagerImpl.getEndpointTransmissionData(SmpLookupManagerImpl.java:163)
        at eu.peppol.outbound.transmission.TransmissionTestModule$2.getEndpointTransmissionData(TransmissionTestModule.j
ava:115)
        at eu.peppol.outbound.transmission.TransmissionRequestBuilder.build(TransmissionRequestBuilder.java:152)
        at eu.peppol.outbound.transmission.TransmissionRequestBuilderTest.xmlWithNoSBDH(TransmissionRequestBuilderTest.j
ava:93)
```

**Comment by tjeb** [comment]
I just ran into this issue as well, and setting the hostname to sml.peppolcentral.org fixed it indeed.

From the looks of it, setting oxalis.operation.mode to TEST changes the default value that is used for oxalis.sml.hostname to smk.peppolcentral.org; whereas setting it to production sets it at sml.peppolcentral.org.

So when changing oxalis.operation.mode to TEST, one must *also* set oxalis.sml.hostname (to sml.peppolcentral.org) in order for the tests to succeed.

The current example file https://github.com/difi/oxalis/blob/master/oxalis-commons/src/main/resources/oxalis-global.properties will fail mvn test (as of commit 2600cb388d77fd9434e6c75687c0e6f9e460cc3b).
