### ISSUE TITLE
Transport Protocol Not Supported - Oxalis Standalone

### ISSUE THREAD

**Issue by mySupply** [OxalisCommunity/oxalis#491]
I'm attempting to send a message to CEF, regarding their connectivity test, using Oxalis Standalone.
My command looks like this:

`java -DOXALIS_HOME=D:/ConnectivityTest/Peppol/outbound/OXALIS_HOME -classpath D:/Intellij/oxalis-standalone-as4/eu.sendregning.oxalis.Main -jar D:/Intellij/oxalis-standalone-as4/standalone/oxalis-standalone-4.1.2.jar -cert D:/Intellij/oxalis-standalone-as4/CefSupportCert.cer -s dynceftest2party55gw -r cefsupport1gw -f D:/Intellij/oxalis-standalone-as4/payload.xml --protocol peppol-transport-as4-v1_0 -u https://qa-ap01-peppol.mysupply.dk/VAX360_Test_oxalis-inbound/as4`

I have not been able to send the message, however. In OXALIS_HOME, i get this error, logged:

`2020-09-22 10:55:04,711 INFO [no.difi.oxalis.commons.security.CertificateModule] [] Certificate subject: EMAILADDRESS=CEF-EDELIVERY-SUPPORT@ec.europa.eu, CN=dynceftest2party55gw, OU=Connecting Europe Facility, O=Connectivity Test, ST=Brussels-Capital, C=BE 
2020-09-22 10:55:04,711 INFO [no.difi.oxalis.commons.security.CertificateModule] [] Certificate issuer: EMAILADDRESS=CEF-EDELIVERY-SUPPORT@ec.europa.eu, CN=Connectivity Test Component CA, OU=Connecting Europe Facility, O=Connectivity Test, ST=Belgium, C=BE 
2020-09-22 10:55:04,722 INFO [no.difi.vefa.peppol.security.ModeDetector] [] Detected mode: TEST 
2020-09-22 10:55:04,727 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] [] Prioritized list of transport profiles: 
2020-09-22 10:55:04,729 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0r1 
2020-09-22 10:55:04,729 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver2p0 
2020-09-22 10:55:04,729 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0 
2020-09-22 10:55:05,808 WARN [no.difi.oxalis.outbound.transmission.TransmissionRequestBuilder] [] Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour. 
2020-09-22 10:55:05,811 ERROR [eu.sendregning.oxalis.Main] [] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: Transport protocol 'peppol-transport-as4-v1_0' not supported. 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: Transport protocol 'peppol-transport-as4-v1_0' not supported.
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: Transport protocol 'peppol-transport-as4-v1_0' not supported.
	at no.difi.oxalis.outbound.transmission.MessageSenderFactory.getSender(MessageSenderFactory.java:108)
	at no.difi.oxalis.outbound.transmission.MessageSenderFactory.getMessageSender(MessageSenderFactory.java:121)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:148)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

Do you know why I have this issue? Our AP should definitely support AS4.

Thank you,

Andreas - mySupply

**Comment by aaron-kumar** [comment]
You are getting right error "Transport protocol 'peppol-transport-as4-v1_0' not supported."

Supported protocols are :
1. busdox-transport-as2-ver2p0
2. peppol-transport-as4-v2_0
3. bdxr-transport-ebms3-as4-v1p0

Below are deprecated protocols:
1. busdox-transport-start
2. busdox-transport-as2-ver1p0 

For details, refer: "TransportProfile.java" class in "https://github.com/OxalisCommunity/vefa-peppol" 

Hope that clarify. If you still have doubt, please write back.
