### ISSUE TITLE
Docker container crashes at startup

### ISSUE THREAD

**Issue by vmax** [OxalisCommunity/oxalis#518]
Attempting to start `norstella/oxalis:5.0.1` image (latest at the time) throws an error:

```
2021-05-29 19:01:52,392  INFO [network.oxalis.server.Main] Starting server 
Exception in thread "main" java.lang.IllegalStateException: StatisticsHandler has no Wrapped Handler
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:251)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at network.oxalis.server.Main.run(Main.java:82)
	at network.oxalis.server.Main.main(Main.java:58)
```

I'm starting the container by bind-mounting keystore file & a config which only contains `oxalis.keystore` section (for passing in password)

**UPD**: `oxalis-server-5.0.1-full.tar.gz` distribution is also affected

**Comment by aaron-kumar** [comment]
Please refer reply : https://github.com/OxalisCommunity/Oxalis-AS4/issues/156#issuecomment-853745762

**Comment by vmax** [comment]
@aaron-kumar I've discovered that not only the Docker image is affected, but also the release hosted on GitHub Releases

**Comment by aaron-kumar** [comment]
@vmax  : Can you share your setting/configuration for regular release? I do not see any issue at least in our deployment. 

P.S. Please note that legacy modules (https://github.com/OxalisCommunity/oxalis/tree/master/oxalis-legacy) will not be supported going forward. Though we haven't removed these modules support yet but they will be remove in due course. Though can be managed as separate repo in future.

**Comment by gozus19p** [comment]
Hi guys!

I am trying to upgrade Oxalis from 4.1.1 to 5.0.1 and I am facing off the same issue as @vmax.
We are trying to refer to Docker Hub [norstella/oxalis-as4:5.0.1](https://hub.docker.com/layers/norstella/oxalis-as4/5.0.1/images/sha256-dab7716b09999d2fa08f963e265e0cfca53a0a19ea1d578755ec25b3eefda7cb?context=explore).

At the moment, I have rolled back to the version previously installed on our systems: digdir/oxalis-as4:4.1.5.

I would like to kindly ask you for an information.
I must plan the Oxalis upgrade date, in order to organize our development team.
Do you have any idea when the pull request will be merged and made available on Docker Hub?
I am asking this just to understand if it is better, for us, to proceed in another way in the meantime.
We would prefer to wait for the official release.

I thought to upgrade from 4.1.5 to 5.0.0, but 5.0.0 version contains a bug on PEPPOL lookup process (fixed in 5.0.1). So, I would go for 5.0.2, maybe.

Many thanks in advance.
I wish you a great day.

Best regards,
Manuel

**Comment by aaron-kumar** [comment]
I will merge the change soon (probably this weekend) and create latest artifact. 

Please verify that latest artifact, available in docker hub. Once you found that it is working as expected, I will create release e.g. 5.0.2.

**Comment by gozus19p** [comment]
Thank you so much. I will try to install the latest artifact on Monday. I will let you know the result as soon as possible.
Have a nice day!

**Comment by aaron-kumar** [comment]
@gozus19p  : Please check latest docker hub release (norstella/oxalis:latest)

**Comment by gozus19p** [comment]
Hi Aaron,

thanks for the update!
I confirm you that I installed the latest Docker Hub release. I found no problems during Docker startup.

I wish you all a great day.

Best regards,
Manuel

**Comment by aaron-kumar** [comment]
@gozus19p & @vmax : This change will be part of 5.0.2 release - I can't commit date now but will be released soon.

**Comment by aaron-kumar** [comment]
@gozus19p  & @vmax  : fix released as part of Oxalis 5.0.3. Docker : norstella/oxalis:5.0.3

**Comment by vmax** [comment]
@aaron-kumar thanks! any chance we could also get a new version of `norstella/oxalis-as4` too up on DockerHub? Then OxalisCommunity/Oxalis-AS4#156 would be fixed too :slightly_smiling_face:

**Comment by aaron-kumar** [comment]
@vmax : Here you go : norstella/oxalis-as4:5.0.2

Either I posted my earlier release message too quickly or you responded too quickly (_I was not expecting early response due to weekend_) 🙂

Please verify and let me know if any issue etc...
