### ISSUE TITLE
Error "No transmission is provided" 

### ISSUE THREAD

**Issue by bergheil** [OxalisCommunity/oxalis#548]
Hi,
we are using the last release of oxalis in docker version.
We are enrolling Peppol testbed and we got the error below when sending back the received message (second step of testbed procedure).
It seems that the url in the error below is not correct; it should be "http://test-smp.peppol.gr/iso6523-actorid-" (we removed "http" after ".gr" and the url is fine).

The certificates should be ok because we passed the first step of testbed peppol.
As receiver of the testbed we used 9906:_VATNUMBER_ (or 0192:810418052).

We attach below our oxalis.conf file taken from [oxalis guide](https://github.com/OxalisCommunity/Oxalis-AS4/blob/master/docs/peppol-test-bed/index.md)

Thanks in advance. Grazie :-)

--------------------------------------- CONFIG -------------------------------------------------
oxalis.keystore: {
    path: oxalis-keystore.jks
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXX"

    key: {
        alias: "pit000XX (peppol access point test ca - g2)"
        password: "XXXXXXXXXXXXXXXXX"
    }
}

# The folder where the incoming messages will be stored
oxalis.path.inbound = /oxalis/inbound/

# Optional
oxalis.logging.config=/oxalis/conf/logback.xml
----------------------------------------------------------------------------------

-------------------- ERROR--------------------------------------
```
Message failed : Unable to fetch 'http://test-smp.peppol.grhttp/iso6523-actorid-upis%3A%3A0088%3Atbcntrl00002/services/busdox-docid-qns%3A%3Aurn%3Aoasis%3Anames%3Aspe
cification%3Aubl%3Aschema%3Axsd%3AInvoice-2%3A%3AInvoice%23%23urn%3Awww.cenbii.eu%3Atransaction%3Abiitrns010%3Aver2.0%3Aextended%3Aurn%3Awww.peppol.eu%3Abis%3Apeppol5
a%3Aver2.0%3A%3A2.1'

ERROR [main] e.s.o.Main [Main.java:230] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748

```

**Comment by aaron-kumar** [comment]
This problem was fixed in Oxalis version 5.0.0 and higher

For Oxalis version prior to 5.0.0, use below property in ‘oxalis.conf’ configuration file:

> lookup.locator.class=no.difi.vefa.peppol.lookup.locator.BusdoxLocator


For details, refer: https://www.oxalis.network/technical-information
