### ISSUE TITLE
Hitting Unable to verify certificate of receiving access point when sending message using standalone jar

### ISSUE THREAD

**Issue by evanswappf** [OxalisCommunity/oxalis#685]
Hi I'm currently trying to send message to oxalis as4 accessPoint using standalone.jar using this command 

`java -classpath "oxalis-distribution-6.7.0-distro/api/*;oxalis-as4-6.7.0-dist/*;oxalis-distribution-6.7.0-distro/bin/*" eu.sendregning.oxalis.Main -f .\sample.xml --cert .\Peppol_AccessPoint_CA.cer -protocol peppol-transport-as4-v2_0 -u https://peppol-ap-testbed.appfuxion.com/as4`

But I received this error instead

```
2024-09-26 10:09:35,756 WARN [network.oxalis.outbound.transmission.TransmissionRequestBuilder] Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour.
2024-09-26 10:09:35,756 ERROR [eu.sendregning.oxalis.Main] Execution failed: network.oxalis.api.lang.OxalisTransmissionException: Unable to verify certificate of receiving access point.
java.util.concurrent.ExecutionException: network.oxalis.api.lang.OxalisTransmissionException: Unable to verify certificate of receiving access point.
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at eu.sendregning.oxalis.Main.main(Main.java:228)
Caused by: network.oxalis.api.lang.OxalisTransmissionException: Unable to verify certificate of receiving access point.
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:162)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: network.oxalis.vefa.peppol.security.lang.PeppolSecurityException: Validation of subject principal(CN) failed.
        at network.oxalis.vefa.peppol.security.util.DifiCertificateValidator.validate(DifiCertificateValidator.java:64)
        at network.oxalis.commons.mode.OxalisCertificateValidator.perform(OxalisCertificateValidator.java:48)
        at network.oxalis.commons.mode.OxalisCertificateValidator.validate(OxalisCertificateValidator.java:38)
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:127)
        ... 10 common frames omitted
Caused by: network.oxalis.commons.certvalidator.api.FailedValidationException: Validation of subject principal(CN) failed.
        at network.oxalis.commons.certvalidator.rule.PrincipalNameRule.validate(PrincipalNameRule.java:68)
        at network.oxalis.commons.certvalidator.structure.AndJunction.validate(AndJunction.java:29)
        at network.oxalis.commons.certvalidator.structure.AbstractJunction.validate(AbstractJunction.java:36)
        at network.oxalis.commons.certvalidator.util.CachedValidatorRule.load(CachedValidatorRule.java:43)
        at network.oxalis.commons.certvalidator.util.CachedValidatorRule.load(CachedValidatorRule.java:13)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3570)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2312)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4011)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4034)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5010)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5017)
        at network.oxalis.commons.certvalidator.util.CachedValidatorRule.validate(CachedValidatorRule.java:30)
        at network.oxalis.commons.certvalidator.util.CachedValidatorRule.validate(CachedValidatorRule.java:35)
        at network.oxalis.commons.certvalidator.ValidatorGroup.validate(ValidatorGroup.java:79)
        at network.oxalis.commons.certvalidator.ValidatorGroup.validate(ValidatorGroup.java:70)
        at network.oxalis.vefa.peppol.security.util.DifiCertificateValidator.validate(DifiCertificateValidator.java:62)
        ... 13 common frames omitted
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1
```
Also may I know whether I'm using the correct cer because we currently only have the following certs and peppol only provide us the cert.p12 file

![image](https://github.com/user-attachments/assets/e721382f-2486-4498-952c-4ca02d9d272c)

Thanks.
Best regards

**Comment by aaron-kumar** [comment]
See combined response in : https://github.com/OxalisCommunity/Oxalis-AS4/issues/261 . This ticket will be closed
