### ISSUE TITLE
"Unable to detect mode" for TestBed message submission

### ISSUE THREAD

**Issue by platomedical** [OxalisCommunity/oxalis#695]
Hi. I am trying out the TestBed. 

I am able to run oxalis for message reception successfully. However, I am facing issues with message submission.

When I try this command:

```
java -classpath "standalone/*:as4/*" eu.sendregning.oxalis.Main  --protocol peppol-transport-as4-v2_0 -f TestFile_001__Invoice.xml 
```

I get the following error:

```
2024-11-05 19:06:24,103 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /Users/user/code/peppol 
2024-11-05 19:06:24,105 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /Users/user/code/peppol 
2024-11-05 19:06:24,106 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /Users/user/code/peppol/oxalis.conf 
2024-11-05 19:06:24,108 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:  
2024-11-05 19:06:24,108 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: /Users/user/code/peppol/inbound 
2024-11-05 19:06:24,108 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: oxalis-plugin 
2024-11-05 19:06:24,309 INFO [network.oxalis.as4.util.OxalisAlgorithmSuiteLoader] Registering OxalisAlgorithmSuite on bus cxf1807894765 
Nov 05, 2024 7:06:24 PM com.sun.xml.bind.v2.runtime.reflect.opt.Injector <clinit>
SEVERE: null
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:575)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:166)
	at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:51)
	at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:157)
	at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:255)
	at com.sun.xml.bind.v2.runtime.property.ArrayProperty.<init>(ArrayProperty.java:38)
	at com.sun.xml.bind.v2.runtime.property.ArrayERProperty.<init>(ArrayERProperty.java:58)
	at com.sun.xml.bind.v2.runtime.property.ArrayElementProperty.<init>(ArrayElementProperty.java:70)
	at com.sun.xml.bind.v2.runtime.property.ArrayElementNodeProperty.<init>(ArrayElementNodeProperty.java:32)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:99)
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:150)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:493)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:310)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1142)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:141)
	at com.sun.xml.bind.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:35)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:358)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at org.apache.xml.security.stax.config.Init.init(Init.java:54)
	at org.apache.wss4j.stax.setup.WSSec.<clinit>(WSSec.java:62)
	at org.apache.cxf.ws.security.wss4j.WSS4JStaxOutInterceptor.<init>(WSS4JStaxOutInterceptor.java:94)
	at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JStaxOutInterceptor.<init>(PolicyBasedWSS4JStaxOutInterceptor.java:45)
	at org.apache.cxf.ws.security.policy.interceptors.WSSecurityInterceptorProvider.<init>(WSSecurityInterceptorProvider.java:65)
	at org.apache.cxf.ws.security.policy.WSSecurityPolicyLoader.registerProviders(WSSecurityPolicyLoader.java:300)
	at org.apache.cxf.ws.security.policy.WSSecurityPolicyLoader.<init>(WSSecurityPolicyLoader.java:108)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.cxf.bus.extension.Extension.load(Extension.java:218)
	at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:198)
	at org.apache.cxf.bus.extension.ExtensionManagerImpl.getBeansOfType(ExtensionManagerImpl.java:333)
	at org.apache.cxf.ws.policy.PolicyInterceptorProviderRegistryImpl.loadDynamic(PolicyInterceptorProviderRegistryImpl.java:93)
	at org.apache.cxf.extension.RegistryImpl.get(RegistryImpl.java:57)
	at org.apache.cxf.ws.policy.PolicyInterceptorProviderRegistryImpl.register(PolicyInterceptorProviderRegistryImpl.java:75)
	at org.apache.cxf.ws.security.policy.WSSecurityPolicyLoader.registerProviders(WSSecurityPolicyLoader.java:299)
	at org.apache.cxf.ws.security.policy.WSSecurityPolicyLoader.<init>(WSSecurityPolicyLoader.java:108)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.cxf.bus.extension.Extension.load(Extension.java:218)
	at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:198)
	at org.apache.cxf.bus.extension.ExtensionManagerImpl.getBeansOfType(ExtensionManagerImpl.java:333)
	at org.apache.cxf.ws.policy.AssertionBuilderRegistryImpl.loadDynamic(AssertionBuilderRegistryImpl.java:96)
	at org.apache.neethi.AssertionBuilderFactoryImpl.registerBuilder(AssertionBuilderFactoryImpl.java:95)
	at network.oxalis.as4.util.OxalisAlgorithmSuiteLoader.register(OxalisAlgorithmSuiteLoader.java:68)
	at network.oxalis.as4.util.OxalisAlgorithmSuiteLoader.lambda$new$0(OxalisAlgorithmSuiteLoader.java:48)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710)
	at network.oxalis.as4.util.OxalisAlgorithmSuiteLoader.<init>(OxalisAlgorithmSuiteLoader.java:40)
	at network.oxalis.as4.common.As4CommonModule.configure(As4CommonModule.java:62)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:66)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at network.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:66)
	at network.oxalis.outbound.OxalisOutboundComponent.<init>(OxalisOutboundComponent.java:45)
	at eu.sendregning.oxalis.Main.main(Main.java:117)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
	at java.base/java.lang.Class.getMethod(Class.java:2405)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:170)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:166)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	... 63 more

Nov 05, 2024 7:06:24 PM org.apache.cxf.ws.security.policy.WSSecurityPolicyLoader <init>
WARNING: Could not load or register WS-SecurityPolicy related classes. Please check that (the correct version of) Apache WSS4J is on the classpath: null
Nov 05, 2024 7:06:24 PM org.apache.cxf.ws.security.policy.WSSecurityPolicyLoader <init>
WARNING: Could not load or register WS-SecurityPolicy related classes. Please check that (the correct version of) Apache WSS4J is on the classpath: Could not initialize class org.apache.wss4j.stax.setup.WSSec
2024-11-05 19:06:24,498 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /Users/user/code/peppol 
2024-11-05 19:06:24,499 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /Users/user/code/peppol 
2024-11-05 19:06:24,499 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /Users/user/code/peppol/oxalis.conf 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TOTAL: 20 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_MAX_ROUTE: 2 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_VALIDATE_AFTER_INACTIVITY: 1000 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TIME_TO_LIVE: 30 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_CONNECT: 0 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_READ: 0 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_SOCKET: 0 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] Error => TRACKER: quiet 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] AS2 => NOTIFICATION: not.in.use@difi.no 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:  
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: /Users/user/code/peppol/inbound 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: oxalis-plugin 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => HOSTNAME:  
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => MSGID_GENERATOR: default 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PATH: /Users/user/code/peppol/staging.p12 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PASSWORD: ************ 
2024-11-05 19:06:24,500 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_ALIAS: cert 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_PASSWORD: ************ 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Header => PARSER: sbdh 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => PAYLOAD: default 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => RECEIPT: default 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => EXCEPTION: default 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => HANDLER: default 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => REPORTER: noop 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => HTTP: <null> 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => TRACER: noop 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => DEFAULT: 50 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => STATISTICS: 50 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Tag => GENERATOR: noop 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Timestamp => SERVICE: system 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Evidence => SERVICE: rem 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => DETECTOR: noop 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => WRAPPER: xml 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Statistics => SERVICE: noop 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] Transmission => VERIFIER: default 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => HOSTNAME:  
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => MSGID_GENERATOR: default 
2024-11-05 19:06:24,501 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => TYPE: peppol 
2024-11-05 19:06:24,502 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => CONFIG: logback.xml 
2024-11-05 19:06:24,502 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => SERVICE: logback 
2024-11-05 19:06:24,502 INFO [network.oxalis.commons.logging.LoggingHandler] Logging service: logback 
Configuring Logback with configuration: /Users/user/code/peppol/logback.xml
2024-11-05 19:06:24,540 INFO [network.oxalis.commons.security.CertificateModule] Certificate subject: CN=PSG000720, OU=PEPPOL TEST AP, O=ABC Pte Ltd, C=SG 
2024-11-05 19:06:24,540 INFO [network.oxalis.commons.security.CertificateModule] Certificate issuer: CN=PEPPOL ACCESS POINT TEST CA - G2, OU=FOR TEST ONLY, O=OpenPEPPOL AISBL, C=BE 
2024-11-05 19:06:24,600 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles: 
2024-11-05 19:06:24,601 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0 
2024-11-05 19:06:24,601 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1 
2024-11-05 19:06:24,601 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0 
2024-11-05 19:06:24,601 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0 
2024-11-05 19:06:24,606 ERROR [network.oxalis.commons.guice.GuiceModuleLoader] Unable to detect mode. 
network.oxalis.api.lang.OxalisLoadingException: Unable to detect mode.
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:77)
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:49)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:59)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at network.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:66)
	at network.oxalis.outbound.OxalisOutboundComponent.<init>(OxalisOutboundComponent.java:45)
	at eu.sendregning.oxalis.Main.main(Main.java:117)
Caused by: network.oxalis.vefa.peppol.common.lang.PeppolLoadingException: Unable to initiate 'class network.oxalis.vefa.peppol.security.util.DifiCertificateValidator'
	at network.oxalis.vefa.peppol.mode.Mode.initiate(Mode.java:125)
	at network.oxalis.vefa.peppol.mode.Mode.initiate(Mode.java:94)
	at network.oxalis.vefa.peppol.security.ModeDetector.detect(ModeDetector.java:46)
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:75)
	... 16 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at network.oxalis.vefa.peppol.mode.Mode.initiate(Mode.java:112)
	... 19 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at network.oxalis.commons.certvalidator.ValidatorLoader.build(ValidatorLoader.java:46)
	at network.oxalis.vefa.peppol.security.util.DifiCertificateValidator.<init>(DifiCertificateValidator.java:53)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 22 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:294)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:66)
	at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:57)
	at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:157)
	at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:255)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.<init>(TransducedAccessor.java:207)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor.get(TransducedAccessor.java:147)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.calcTransducer(RuntimeClassInfoImpl.java:215)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.getTransducer(RuntimeClassInfoImpl.java:189)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.link(RuntimeClassInfoImpl.java:166)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.link(ModelBuilder.java:424)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.link(RuntimeModelBuilder.java:103)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:448)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:282)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1142)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:141)
	at com.sun.xml.bind.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:35)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:358)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at network.oxalis.commons.certvalidator.ValidatorLoaderParser.<clinit>(ValidatorLoaderParser.java:32)
	... 25 common frames omitted
Exception in thread "main" network.oxalis.api.lang.OxalisLoadingException: Unable to load Oxalis due to errors during loading.
	at network.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:76)
	at network.oxalis.outbound.OxalisOutboundComponent.<init>(OxalisOutboundComponent.java:45)
	at eu.sendregning.oxalis.Main.main(Main.java:117)
```

Any pointers on what I should check? Thanks so much :)

**Comment by aaron-kumar** [comment]
@platomedical If you are using Java 17 or higher, you will face this exception. Workaround for this is to SET:
`JDK_JAVA_OPTIONS= --add-opens=java.base/java.lang=ALL-UNNAMED `
OR VM Parameters:
`VMARGS=--add-opens java.base/java.lang=ALL-UNNAMED`

It is fixed as part of Oxalis 7.x (_currently in beta release_)

**Comment by aaron-kumar** [comment]
Converting this to discussion...
